---
- name: Install packages
  become: yes
  become_method: sudo
  vars:
    compose_path: /usr/local/bin/docker-compose
  block:
  - name: Ensure built-in docker is removed
    apt:
      pkg:
      - docker
      - docker-engine
      - docker.io
      state: absent

  - name: Install docker GPG
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Install docker apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      update_cache: yes

  - name: Install docker-ce
    apt:
      name: docker-ce
      state: latest

  - name: Install dependencies
    apt:
      pkg:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Check if docker-compose is installed
    stat:
      path: "{{ compose_path }}"
    register: compose_is_installed

  - name: Check docker-compose version
    when: "compose_is_installed.stat.exists"
    command: "{{ compose_path }} version"
    register: compose_read_version
    changed_when: False
    failed_when: False

  - name: Install Docker Compose
    when: "'not found' in compose_read_version.stdout"
    get_url:
      url: "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64"
      dest: "/usr/local/bin/docker-compose"
      mode: u+x,g+x,o+x

- name: "Remember to add docker group to users!"
  debug:
    msg: Remember to add docker groups to users with "sudo usermod -aG docker $USER".
